### ISSUE TITLE
Connection fails

### ISSUE THREAD

**Issue by ShadyElyaski** [lukedemi/gdax-notifier#2]
When trying to run docker, I get the following error:-

bundler: failed to load command: ./run.rb (./run.rb)
Coinbase::Exchange::BadRequestError: {"message":"request timestamp expired"}
  /usr/local/bundle/bundler/gems/coinbase-exchange-ruby-2c4b3f91346a/lib/coinbase/exchange/adapters/net_http.rb:38:in `http_verb'
  /usr/local/bundle/bundler/gems/coinbase-exchange-ruby-2c4b3f91346a/lib/coinbase/exchange/api_client.rb:285:in `get'
  /usr/local/bundle/bundler/gems/coinbase-exchange-ruby-2c4b3f91346a/lib/coinbase/exchange/api_client.rb:209:in `fills'
  /usr/src/app/lib/notifier.rb:24:in `fills'
  /usr/src/app/lib/notifier.rb:20:in `create_fill_cache'
  /usr/src/app/lib/notifier.rb:16:in `initialize'
  /usr/src/app/run.rb:5:in `new'
  /usr/src/app/run.rb:5:in `<top (required)>'

**Comment by lukedemi** [comment]
will take a look, thanks for the heads up

**Comment by juanezamudio** [comment]
Figured out that it was an error with my machine's clock being out of sync. Try running:

`sudo ntpdate -u time.apple.com`

That seemed to do it for me. Replace the time server name if you're using a different server.
